apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userprofile-blue-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Alekhyacloud19/AWS-Retail-App.git
    targetRevision: dev
    path: Retail-chart
    helm:
      values: |
        userprofile:
          activeVersion: blue
  destination:
    server: https://3193F99F1C8D27FD62FD6000F59E226A.gr7.us-east-2.eks.amazonaws.com
    namespace: retail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
